name: Run Swagger Tests

on:
  push:
    branches:
      - feature/workflow-cicd-file

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Restore dependencies
        run: dotnet restore Swagger.Tests.sln # Specify solution file here
        working-directory: ./SwaggerProj/Swagger.Tests # Directory containing the .sln file

      - name: Build
        run: dotnet build Swagger.Tests.sln --configuration Release --no-restore
        working-directory: ./SwaggerProj/Swagger.Tests

      - name: Run tests
        run: dotnet test Swagger.Tests.sln --configuration Release --no-build --verbosity normal
        working-directory: ./SwaggerProj/Swagger.Tests
