name: Run Swagger Tests

on:
  push:
    branches:
      - feature/workflow-cicd-file

jobs:
  test:
    runs-on: ubuntu-latest # or windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x" # or your .NET version

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./SwaggerProj

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./SwaggerProj

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal
        working-directory: ./SwaggerProj
